"""
Local HS codes dataset for keyword search.
Covers the most common product categories used in international courier shipments.
Format: list of dicts with keys: htsno, description, general (duty rate)
"""

HS_CODES = [
    # Chapter 1-5: Live Animals & Animal Products
    {"htsno": "0101.21", "description": "Live horses, pure-bred breeding", "general": "Free"},
    {"htsno": "0101.29", "description": "Live horses, other than pure-bred breeding", "general": "4.5%"},
    {"htsno": "0201.10", "description": "Beef, carcasses and half-carcasses, fresh or chilled", "general": "26.4%"},
    {"htsno": "0207.11", "description": "Chicken, not cut in pieces, fresh or chilled", "general": "8.8%"},
    {"htsno": "0302.11", "description": "Trout, fresh or chilled", "general": "Free"},
    {"htsno": "0401.10", "description": "Milk and cream, not concentrated, fat content ≤1%", "general": "1.46¢/liter"},
    {"htsno": "0406.10", "description": "Fresh (unripened or uncured) cheese", "general": "10%"},
    {"htsno": "0408.11", "description": "Dried egg yolks", "general": "8.7 ¢/kg"},

    # Chapter 6-14: Vegetable Products
    {"htsno": "0601.10", "description": "Bulbs, tubers, tuberous roots, corms for planting", "general": "Free"},
    {"htsno": "0701.10", "description": "Potatoes, seed, fresh or chilled", "general": "Free"},
    {"htsno": "0805.10", "description": "Oranges, fresh or dried", "general": "1.9¢/kg"},
    {"htsno": "0901.11", "description": "Coffee, not roasted, not decaffeinated", "general": "Free"},
    {"htsno": "0902.10", "description": "Green tea (not fermented)", "general": "Free"},
    {"htsno": "1001.11", "description": "Durum wheat, seed", "general": "Free"},
    {"htsno": "1006.10", "description": "Rice in the husk (paddy or rough)", "general": "Free"},

    # Chapter 15: Animal or Vegetable Fats
    {"htsno": "1507.10", "description": "Crude soybean oil for technical or industrial uses", "general": "Free"},
    {"htsno": "1511.10", "description": "Crude palm oil for technical or industrial uses", "general": "Free"},

    # Chapter 16-24: Prepared Foodstuffs
    {"htsno": "1602.31", "description": "Prepared or preserved turkey", "general": "6.4%"},
    {"htsno": "1704.10", "description": "Chewing gum, whether or not sugar-coated", "general": "4%"},
    {"htsno": "1806.10", "description": "Cocoa powder, containing added sugar or sweetening", "general": "Free"},
    {"htsno": "1806.31", "description": "Chocolate, in blocks/slabs/bars, filled", "general": "6%"},
    {"htsno": "1901.10", "description": "Preparations for infant use, put up for retail sale", "general": "14.9%"},
    {"htsno": "1905.31", "description": "Sweet biscuits", "general": "Free"},
    {"htsno": "2009.11", "description": "Frozen orange juice", "general": "7.85¢/liter"},
    {"htsno": "2101.11", "description": "Extracts, essences and concentrates of coffee", "general": "Free"},
    {"htsno": "2106.90", "description": "Food preparations, not elsewhere specified", "general": "6.4%"},
    {"htsno": "2202.10", "description": "Waters, including mineral waters and aerated waters, containing added sugar", "general": "Free"},
    {"htsno": "2204.10", "description": "Sparkling wine", "general": "19.8¢/liter"},
    {"htsno": "2208.30", "description": "Whiskies", "general": "Free"},

    # Chapter 25-27: Mineral Products
    {"htsno": "2523.10", "description": "Cement clinkers", "general": "Free"},
    {"htsno": "2701.11", "description": "Anthracite coal", "general": "Free"},
    {"htsno": "2710.12", "description": "Light petroleum oils and preparations", "general": "52.5¢/bbl"},

    # Chapter 28-38: Chemical Products
    {"htsno": "2804.10", "description": "Hydrogen", "general": "3.7%"},
    {"htsno": "2833.11", "description": "Disodium sulphate", "general": "Free"},
    {"htsno": "2901.10", "description": "Acyclic hydrocarbons, saturated", "general": "Free"},
    {"htsno": "2936.21", "description": "Vitamins A and their derivatives", "general": "Free"},
    {"htsno": "3002.12", "description": "Vaccines for human medicine", "general": "Free"},
    {"htsno": "3004.10", "description": "Medicines containing penicillins", "general": "Free"},
    {"htsno": "3004.50", "description": "Medicines containing vitamins", "general": "Free"},
    {"htsno": "3004.90", "description": "Other medicaments for retail sale", "general": "Free"},
    {"htsno": "3006.10", "description": "Sterile surgical catgut and suture materials", "general": "Free"},
    {"htsno": "3101.00", "description": "Animal or vegetable fertilizers", "general": "Free"},
    {"htsno": "3204.11", "description": "Disperse dyes and preparations", "general": "7.4%"},
    {"htsno": "3301.12", "description": "Essential oils of orange", "general": "Free"},
    {"htsno": "3401.11", "description": "Soap for toilet use", "general": "Free"},
    {"htsno": "3402.20", "description": "Preparations put up for retail sale as detergents", "general": "Free"},
    {"htsno": "3406.00", "description": "Candles, tapers and the like", "general": "Free"},

    # Chapter 39-40: Plastics and Rubber
    {"htsno": "3901.10", "description": "Polyethylene having a specific gravity of less than 0.94", "general": "Free"},
    {"htsno": "3923.10", "description": "Boxes, cases, crates and similar articles of plastics", "general": "3%"},
    {"htsno": "3924.10", "description": "Tableware and kitchenware of plastics", "general": "3.4%"},
    {"htsno": "3926.20", "description": "Articles of apparel and clothing accessories of plastics", "general": "5%"},
    {"htsno": "4011.10", "description": "New pneumatic tyres for motor cars", "general": "4%"},
    {"htsno": "4016.93", "description": "Gaskets, washers and other seals of vulcanized rubber", "general": "Free"},

    # Chapter 41-43: Raw Hides, Skins and Leather
    {"htsno": "4107.11", "description": "Full grain unsplit leather of bovine origin", "general": "2.8%"},
    {"htsno": "4203.10", "description": "Articles of apparel of leather", "general": "6%"},
    {"htsno": "4205.00", "description": "Other articles of leather or composition leather", "general": "Free"},

    # Chapter 44-46: Wood and Wood Products
    {"htsno": "4407.11", "description": "Pine (Pinus spp.) wood sawn or chipped lengthwise", "general": "Free"},
    {"htsno": "4412.10", "description": "Plywood of bamboo", "general": "8%"},
    {"htsno": "4418.10", "description": "Windows, french windows and their frames of wood", "general": "Free"},
    {"htsno": "4421.91", "description": "Articles of wood, of bamboo", "general": "3.2%"},

    # Chapter 47-49: Paper and Paperboard
    {"htsno": "4802.10", "description": "Handmade paper and paperboard", "general": "Free"},
    {"htsno": "4819.10", "description": "Cartons, boxes and cases of corrugated paper", "general": "Free"},
    {"htsno": "4901.10", "description": "Books, brochures and similar printed matter, in single sheets", "general": "Free"},
    {"htsno": "4901.91", "description": "Printed books, dictionaries, encyclopaedias", "general": "Free"},
    {"htsno": "4901.99", "description": "Other books, brochures, leaflets", "general": "Free"},
    {"htsno": "4902.10", "description": "Newspapers, journals and periodicals, daily", "general": "Free"},
    {"htsno": "4903.00", "description": "Children's picture, drawing or colouring books", "general": "Free"},
    {"htsno": "4904.00", "description": "Music, printed or in manuscript", "general": "Free"},
    {"htsno": "4905.00", "description": "Maps and hydrographic or similar charts", "general": "Free"},
    {"htsno": "4907.00", "description": "Unused postage, revenue or similar stamps, banknotes", "general": "Free"},
    {"htsno": "4909.00", "description": "Printed or illustrated postcards", "general": "Free"},
    {"htsno": "4910.00", "description": "Calendars, printed, of any kind", "general": "Free"},
    {"htsno": "4911.10", "description": "Trade advertising material, commercial catalogues", "general": "Free"},

    # Chapter 50-63: Textiles
    {"htsno": "5007.10", "description": "Woven fabrics of noil silk", "general": "4.4%"},
    {"htsno": "5208.11", "description": "Plain woven cotton fabric, unbleached, ≤100g/m²", "general": "7.5%"},
    {"htsno": "5515.11", "description": "Woven fabrics of polyester staple fibres mixed with viscose", "general": "12%"},
    {"htsno": "5601.21", "description": "Cotton wadding, articles thereof", "general": "3.4%"},
    {"htsno": "5903.10", "description": "Textile fabrics impregnated with polyvinyl chloride", "general": "2.7%"},
    {"htsno": "6101.20", "description": "Men's overcoats, car-coats of cotton, knitted", "general": "16%"},
    {"htsno": "6104.11", "description": "Women's suits of wool or fine animal hair, knitted", "general": "12%"},
    {"htsno": "6104.12", "description": "Women's suits of cotton, knitted", "general": "11.9%"},
    {"htsno": "6104.13", "description": "Women's suits of man-made fibres, knitted", "general": "24.9%"},
    {"htsno": "6104.19", "description": "Women's suits of other textile materials, knitted", "general": "6.5%"},
    {"htsno": "6104.61", "description": "Women's trousers of wool or fine animal hair, knitted", "general": "16%"},
    {"htsno": "6104.62", "description": "Women's trousers of cotton, knitted", "general": "14.9%"},
    {"htsno": "6104.63", "description": "Women's trousers of synthetic fibres, knitted", "general": "28.2%"},
    {"htsno": "6204.11", "description": "Women's suits of wool or fine animal hair, not knitted", "general": "13.5%"},
    {"htsno": "6204.12", "description": "Women's suits of cotton, not knitted", "general": "9.4%"},
    {"htsno": "6204.13", "description": "Women's suits of man-made fibres, not knitted", "general": "19.7%"},
    {"htsno": "6204.19", "description": "Women's suits of other textile materials, not knitted", "general": "6.4%"},
    {"htsno": "6204.21", "description": "Women's ensembles of wool or fine animal hair, not knitted", "general": "13.5%"},
    {"htsno": "6204.22", "description": "Women's ensembles of cotton, not knitted", "general": "11.5%"},
    {"htsno": "6204.23", "description": "Women's ensembles of synthetic fibres, not knitted", "general": "16.1%"},
    {"htsno": "6109.10", "description": "T-shirts, singlets and other vests, of cotton, knitted", "general": "16.5%"},
    {"htsno": "6109.90", "description": "T-shirts, singlets and other vests, of other textile materials", "general": "32%"},
    {"htsno": "6110.20", "description": "Jerseys, pullovers, sweatshirts of cotton, knitted", "general": "16.5%"},
    {"htsno": "6110.30", "description": "Jerseys, pullovers, sweatshirts of man-made fibres, knitted", "general": "32%"},
    {"htsno": "6111.20", "description": "Babies' garments and clothing accessories of cotton, knitted", "general": "11.5%"},
    {"htsno": "6115.10", "description": "Graduated compression hosiery, knitted", "general": "Free"},
    {"htsno": "6201.20", "description": "Men's overcoats, car-coats of cotton, not knitted", "general": "9.4%"},
    {"htsno": "6203.42", "description": "Men's trousers of cotton, not knitted", "general": "16.6%"},
    {"htsno": "6204.62", "description": "Women's trousers of cotton, not knitted", "general": "16.6%"},
    {"htsno": "6206.10", "description": "Women's blouses, shirts of silk", "general": "1.1%"},
    {"htsno": "6207.11", "description": "Men's underpants and briefs of cotton", "general": "11.4%"},
    {"htsno": "6212.10", "description": "Brassieres", "general": "16.9%"},
    {"htsno": "6301.10", "description": "Electric blankets", "general": "10.5%"},
    {"htsno": "6302.10", "description": "Bed linen, knitted or crocheted", "general": "14.9%"},
    {"htsno": "6302.21", "description": "Bed linen of cotton, printed, not knitted", "general": "14.9%"},
    {"htsno": "6303.12", "description": "Curtains, drapes of cotton, knitted", "general": "11.4%"},
    {"htsno": "6304.11", "description": "Bedspreads, knitted or crocheted", "general": "12%"},
    {"htsno": "6305.10", "description": "Sacks and bags of jute or other textile bast fibres", "general": "Free"},
    {"htsno": "6306.12", "description": "Tarpaulins, awnings and sunblinds of cotton", "general": "3.8%"},
    {"htsno": "6307.10", "description": "Floor-cloths, dish-cloths, dusters of cotton", "general": "7.4%"},
    {"htsno": "6308.00", "description": "Needlecraft sets for tapestry", "general": "Free"},
    {"htsno": "6309.00", "description": "Worn clothing and other worn articles", "general": "Free"},
    {"htsno": "6310.10", "description": "Used or new rags, sorted", "general": "Free"},

    # Chapter 64: Footwear
    {"htsno": "6401.10", "description": "Waterproof footwear with metal toecap, rubber or plastic", "general": "37.5%"},
    {"htsno": "6403.11", "description": "Sports footwear, ski-boots, cross-country ski footwear, leather", "general": "6%"},
    {"htsno": "6403.51", "description": "Footwear with leather uppers covering the ankle", "general": "8.5%"},
    {"htsno": "6403.91", "description": "Other footwear with leather uppers", "general": "10%"},
    {"htsno": "6404.11", "description": "Sports footwear, tennis, basketball shoes, textile uppers", "general": "10.5%"},
    {"htsno": "6404.19", "description": "Other footwear with textile uppers, rubber or plastics soles", "general": "9%"},
    {"htsno": "6405.10", "description": "Other footwear with leather uppers", "general": "10%"},

    # Chapter 65: Headgear
    {"htsno": "6505.00", "description": "Hats and other headgear, knitted or crocheted", "general": "13.5%"},
    {"htsno": "6506.10", "description": "Safety headgear (helmets)", "general": "Free"},
    {"htsno": "6506.99", "description": "Other headgear, not elsewhere specified", "general": "3.9%"},

    # Chapter 68-70: Articles of Stone, Plaster, Cement
    {"htsno": "6802.10", "description": "Tiles, cubes and similar articles of marble", "general": "4.2%"},
    {"htsno": "6910.10", "description": "Ceramic sinks, washbasins, pedestals", "general": "Free"},
    {"htsno": "7013.22", "description": "Drinking glasses of lead crystal", "general": "3%"},
    {"htsno": "7013.49", "description": "Other glassware for table use", "general": "7.2%"},

    # Chapter 71: Precious Metals, Jewellery
    {"htsno": "7101.10", "description": "Natural pearls", "general": "Free"},
    {"htsno": "7102.10", "description": "Diamonds, unsorted", "general": "Free"},
    {"htsno": "7103.10", "description": "Precious stones, unworked or simply sawn", "general": "Free"},
    {"htsno": "7108.12", "description": "Non-monetary gold in non-powder form, unwrought", "general": "Free"},
    {"htsno": "7113.11", "description": "Articles of silver jewellery and parts thereof", "general": "13.5%"},
    {"htsno": "7113.19", "description": "Articles of other precious metal jewellery", "general": "6.5%"},
    {"htsno": "7114.11", "description": "Articles of silversmithing", "general": "3%"},
    {"htsno": "7116.10", "description": "Articles of natural or cultured pearls", "general": "Free"},
    {"htsno": "7117.11", "description": "Cuff links and studs, imitation jewellery", "general": "8%"},
    {"htsno": "7117.19", "description": "Other imitation jewellery of base metal", "general": "11%"},
    {"htsno": "7117.90", "description": "Other imitation jewellery", "general": "11%"},
    {"htsno": "7118.10", "description": "Coin, not being legal tender", "general": "Free"},

    # Chapter 72-83: Base Metals
    {"htsno": "7204.10", "description": "Waste and scrap of cast iron", "general": "Free"},
    {"htsno": "7208.10", "description": "Flat-rolled products of iron or steel, in coils", "general": "Free"},
    {"htsno": "7306.30", "description": "Other tubes, pipes and hollow profiles, welded, of iron or steel", "general": "Free"},
    {"htsno": "7318.11", "description": "Coach screws of iron or steel", "general": "Free"},
    {"htsno": "7323.10", "description": "Iron or steel wool; pot scourers and scouring or polishing pads", "general": "Free"},
    {"htsno": "7324.10", "description": "Sinks and washbasins of stainless steel", "general": "3.4%"},
    {"htsno": "7612.10", "description": "Collapsible tubular containers of aluminium", "general": "5.7%"},
    {"htsno": "7615.10", "description": "Table, kitchen or other household articles of aluminium", "general": "3.1%"},
    {"htsno": "8210.00", "description": "Hand-operated mechanical appliances for preparing food", "general": "3.7%"},
    {"htsno": "8302.10", "description": "Hinges of base metal", "general": "2.9%"},
    {"htsno": "8302.20", "description": "Castors of base metal", "general": "5.7%"},
    {"htsno": "8303.00", "description": "Armoured or reinforced safes, strong-boxes", "general": "Free"},
    {"htsno": "8304.00", "description": "Filing cabinets, card-index cabinets, paper trays", "general": "Free"},
    {"htsno": "8306.21", "description": "Statuettes and other ornaments, of base metal, plated", "general": "Free"},

    # Chapter 84: Nuclear Reactors, Boilers, Machinery
    {"htsno": "8414.51", "description": "Table, floor, wall, window, ceiling or roof fans, with self-contained motor", "general": "4.7%"},
    {"htsno": "8415.10", "description": "Air conditioning machines for motor vehicles, self-contained", "general": "Free"},
    {"htsno": "8418.10", "description": "Combined refrigerator-freezers, with separate external doors", "general": "Free"},
    {"htsno": "8418.21", "description": "Household refrigerators, compression-type", "general": "Free"},
    {"htsno": "8422.11", "description": "Household dishwashing machines", "general": "Free"},
    {"htsno": "8423.10", "description": "Personal weighing machines, including baby scales", "general": "Free"},
    {"htsno": "8424.20", "description": "Spray guns and similar appliances", "general": "1.4%"},
    {"htsno": "8443.31", "description": "Inkjet printing machines", "general": "Free"},
    {"htsno": "8443.32", "description": "Other laser printers", "general": "Free"},
    {"htsno": "8450.11", "description": "Household fully-automatic washing machines, capacity ≤10 kg", "general": "Free"},
    {"htsno": "8452.10", "description": "Household sewing machines", "general": "Free"},
    {"htsno": "8467.11", "description": "Drills of all kinds, rotary, pneumatic", "general": "Free"},
    {"htsno": "8467.21", "description": "Drills of all kinds, rotary, with self-contained electric motor", "general": "Free"},
    {"htsno": "8468.10", "description": "Hand-held blow pipes", "general": "Free"},
    {"htsno": "8471.30", "description": "Portable automatic data processing machines (laptops, notebooks), weighing ≤10 kg", "general": "Free"},
    {"htsno": "8471.41", "description": "Other automatic data processing machines, comprising a CPU and storage", "general": "Free"},
    {"htsno": "8471.49", "description": "Other automatic data processing machines presented in form of systems", "general": "Free"},
    {"htsno": "8471.50", "description": "Processing units for automatic data processing machines", "general": "Free"},
    {"htsno": "8471.60", "description": "Computer keyboards, mice and input or output units for ADP machines", "general": "Free"},
    {"htsno": "8471.70", "description": "Storage units for ADP machines (hard drives, SSDs)", "general": "Free"},
    {"htsno": "8471.80", "description": "Other units of ADP machines", "general": "Free"},
    {"htsno": "8473.30", "description": "Parts and accessories for ADP machines and units thereof", "general": "Free"},
    {"htsno": "8504.40", "description": "Static converters (power adapters, chargers)", "general": "Free"},

    # Chapter 85: Electrical Machinery and Equipment
    {"htsno": "8501.10", "description": "Motors of an output not exceeding 37.5 W", "general": "Free"},
    {"htsno": "8502.11", "description": "Generating sets with compression-ignition engines, ≤75 kVA", "general": "Free"},
    {"htsno": "8507.10", "description": "Lead-acid batteries for starting piston engines", "general": "3.5%"},
    {"htsno": "8507.20", "description": "Other lead-acid batteries (sealed, rechargeable)", "general": "3.5%"},
    {"htsno": "8507.60", "description": "Lithium-ion batteries", "general": "3.4%"},
    {"htsno": "8507.80", "description": "Power banks, portable lithium battery packs for charging devices", "general": "3.4%"},
    {"htsno": "8508.11", "description": "Vacuum cleaners, of a power ≤1,500 W, with bag/other container capacity ≤20 litres", "general": "Free"},
    {"htsno": "8509.40", "description": "Food grinders and mixers; fruit or vegetable juice extractors", "general": "Free"},
    {"htsno": "8510.10", "description": "Shavers, with self-contained electric motor", "general": "Free"},
    {"htsno": "8510.20", "description": "Hair clippers, with self-contained electric motor", "general": "Free"},
    {"htsno": "8513.10", "description": "Lamps for portable use (flashlights, torches)", "general": "12.5%"},
    {"htsno": "8516.31", "description": "Electrothermic hair dryers", "general": "Free"},
    {"htsno": "8516.50", "description": "Microwave ovens", "general": "Free"},
    {"htsno": "8516.60", "description": "Other ovens, cookers, cooking plates, rings, grills", "general": "Free"},
    {"htsno": "8517.11", "description": "Line telephone sets with cordless handsets", "general": "Free"},
    {"htsno": "8517.12", "description": "Mobile phones (smartphones, cell phones)", "general": "Free"},
    {"htsno": "8517.13", "description": "Smartphones", "general": "Free"},
    {"htsno": "8517.18", "description": "Other telephone sets", "general": "Free"},
    {"htsno": "8517.61", "description": "Base stations for wireless telephony", "general": "Free"},
    {"htsno": "8518.10", "description": "Microphones and stands therefor", "general": "4.9%"},
    {"htsno": "8518.21", "description": "Single loudspeakers, mounted in their enclosures", "general": "Free"},
    {"htsno": "8518.22", "description": "Multiple loudspeakers, mounted in the same enclosure", "general": "Free"},
    {"htsno": "8518.30", "description": "Headphones, earphones and combined microphone/speaker sets", "general": "4.9%"},
    {"htsno": "8518.40", "description": "Audio-frequency electric amplifiers", "general": "Free"},
    {"htsno": "8519.20", "description": "Apparatus operated by coins, banknotes, tokens", "general": "Free"},
    {"htsno": "8519.81", "description": "Other sound-recording or reproducing apparatus (MP3 players)", "general": "Free"},
    {"htsno": "8521.10", "description": "Magnetic tape-type video recording or reproducing apparatus", "general": "Free"},
    {"htsno": "8521.90", "description": "Other video recording or reproducing apparatus (DVD recorders)", "general": "Free"},
    {"htsno": "8522.10", "description": "Pick-up cartridges", "general": "Free"},
    {"htsno": "8523.21", "description": "Unrecorded magnetic discs", "general": "Free"},
    {"htsno": "8523.29", "description": "Other unrecorded magnetic storage media (USB drives, memory cards)", "general": "Free"},
    {"htsno": "8523.49", "description": "Other optical media (DVDs, Blu-rays, CDs)", "general": "Free"},
    {"htsno": "8523.51", "description": "Solid-state non-volatile storage devices (SSDs, flash drives)", "general": "Free"},
    {"htsno": "8525.50", "description": "Transmission apparatus for radio-broadcasting or TV", "general": "Free"},
    {"htsno": "8525.81", "description": "Digital cameras", "general": "Free"},
    {"htsno": "8525.89", "description": "Other cameras (video cameras, camcorders)", "general": "Free"},
    {"htsno": "8527.91", "description": "Radio-broadcast receivers combined with sound-recording or reproducing apparatus", "general": "Free"},
    {"htsno": "8528.52", "description": "Monitors capable of directly connecting to ADP machines (computer monitors)", "general": "Free"},
    {"htsno": "8528.59", "description": "Other monitors, not designed to incorporate video display apparatus", "general": "Free"},
    {"htsno": "8528.72", "description": "Colour television reception apparatus", "general": "Free"},
    {"htsno": "8533.10", "description": "Fixed carbon resistors", "general": "Free"},
    {"htsno": "8534.00", "description": "Printed circuits", "general": "Free"},
    {"htsno": "8536.50", "description": "Switches for voltage ≤1,000 V (light switches)", "general": "Free"},
    {"htsno": "8536.69", "description": "Other plugs and sockets (electrical connectors)", "general": "Free"},
    {"htsno": "8537.10", "description": "Boards, panels, consoles for electrical control ≤1,000 V", "general": "Free"},
    {"htsno": "8541.10", "description": "Diodes, other than photosensitive or light emitting diodes", "general": "Free"},
    {"htsno": "8541.21", "description": "Transistors, other than photosensitive transistors, dissipation rate < 1W", "general": "Free"},
    {"htsno": "8541.40", "description": "Photosensitive semiconductor devices; light emitting diodes (LED)", "general": "Free"},
    {"htsno": "8542.31", "description": "Processors and controllers (CPUs, microprocessors)", "general": "Free"},
    {"htsno": "8542.32", "description": "Memories (RAM, ROM chips)", "general": "Free"},
    {"htsno": "8542.33", "description": "Amplifiers (integrated circuit amplifiers)", "general": "Free"},
    {"htsno": "8542.39", "description": "Other electronic integrated circuits", "general": "Free"},
    {"htsno": "8543.70", "description": "Other electrical machines and apparatus (drones, robots)", "general": "Free"},
    {"htsno": "8544.11", "description": "Winding wire of copper, insulated", "general": "Free"},
    {"htsno": "8544.19", "description": "Winding wire, other (insulated wire)", "general": "Free"},
    {"htsno": "8544.42", "description": "Other electric conductors, fitted with connectors, voltage ≤80 V (USB cables)", "general": "Free"},
    {"htsno": "8544.49", "description": "Other electric conductors, voltage ≤1,000 V (power cables)", "general": "Free"},
    {"htsno": "8545.11", "description": "Carbon electrodes for electric furnaces", "general": "Free"},

    # Chapter 87: Vehicles
    {"htsno": "8701.20", "description": "Road tractors for semi-trailers", "general": "4%"},
    {"htsno": "8702.10", "description": "Motor vehicles for the transport of ten or more persons, diesel", "general": "Free"},
    {"htsno": "8703.21", "description": "Automobiles with cylinder capacity ≤1,000 cc", "general": "2.5%"},
    {"htsno": "8703.22", "description": "Automobiles with cylinder capacity 1,000–1,500 cc", "general": "2.5%"},
    {"htsno": "8703.23", "description": "Automobiles with cylinder capacity 1,500–3,000 cc", "general": "2.5%"},
    {"htsno": "8703.24", "description": "Automobiles with cylinder capacity > 3,000 cc", "general": "2.5%"},
    {"htsno": "8703.80", "description": "Other motor vehicles (hybrid vehicles, electric cars)", "general": "2.5%"},
    {"htsno": "8704.21", "description": "Motor vehicles for transport of goods, diesel, GVW ≤5 tonnes", "general": "25%"},
    {"htsno": "8711.20", "description": "Motorcycles with reciprocating piston engines, 50–250 cc", "general": "Free"},
    {"htsno": "8712.00", "description": "Bicycles and other cycles, not motorised", "general": "11%"},
    {"htsno": "8713.10", "description": "Wheelchairs not mechanically propelled", "general": "Free"},
    {"htsno": "8714.11", "description": "Saddles for motorcycles", "general": "Free"},
    {"htsno": "8716.10", "description": "Trailers and semi-trailers for housing or camping", "general": "Free"},

    # Chapter 88-89: Aircraft, Spacecraft, Ships
    {"htsno": "8801.00", "description": "Balloons and dirigibles; gliders, hang gliders", "general": "Free"},
    {"htsno": "8802.11", "description": "Helicopters of an unladen weight ≤2,000 kg", "general": "Free"},
    {"htsno": "8802.20", "description": "Aeroplanes and other aircraft of an unladen weight ≤2,000 kg", "general": "Free"},
    {"htsno": "8804.00", "description": "Parachutes and rotochutes", "general": "Free"},
    {"htsno": "8805.10", "description": "Aircraft launching gear; deck-arrestor gear", "general": "Free"},

    # Chapter 90: Optical, Photographic, Measuring Instruments
    {"htsno": "9001.10", "description": "Optical fibres and optical fibre bundles", "general": "Free"},
    {"htsno": "9001.40", "description": "Spectacle lenses of glass", "general": "Free"},
    {"htsno": "9003.11", "description": "Frames and mountings for spectacles, of plastics", "general": "Free"},
    {"htsno": "9004.10", "description": "Sunglasses", "general": "2%"},
    {"htsno": "9006.51", "description": "Digital cameras for photography", "general": "Free"},
    {"htsno": "9008.50", "description": "Projectors", "general": "3.9%"},
    {"htsno": "9013.80", "description": "Liquid crystal devices, laser devices (LCD screens, OLED)", "general": "Free"},
    {"htsno": "9015.10", "description": "Rangefinders", "general": "Free"},
    {"htsno": "9017.10", "description": "Drafting tables and machines", "general": "Free"},
    {"htsno": "9018.11", "description": "Electro-diagnostic apparatus (ECG machines)", "general": "Free"},
    {"htsno": "9018.19", "description": "Other electro-diagnostic apparatus", "general": "Free"},
    {"htsno": "9018.31", "description": "Syringes, with or without needles", "general": "Free"},
    {"htsno": "9018.39", "description": "Other needles, catheters, cannulae for medical use", "general": "Free"},
    {"htsno": "9018.41", "description": "Dental drill engines", "general": "Free"},
    {"htsno": "9019.10", "description": "Mechano-therapy appliances; massage apparatus", "general": "Free"},
    {"htsno": "9020.00", "description": "Other breathing appliances and gas masks (oxygen masks)", "general": "Free"},
    {"htsno": "9021.10", "description": "Orthopedic or fracture appliances (braces, casts)", "general": "Free"},
    {"htsno": "9021.21", "description": "Artificial teeth", "general": "Free"},
    {"htsno": "9021.31", "description": "Artificial joints (hip, knee replacements)", "general": "Free"},
    {"htsno": "9021.39", "description": "Other artificial parts of the body (implants, prosthetics)", "general": "Free"},
    {"htsno": "9021.40", "description": "Hearing aids (excluding parts and accessories)", "general": "Free"},
    {"htsno": "9022.12", "description": "CT scanners", "general": "Free"},
    {"htsno": "9022.14", "description": "X-ray apparatus for dental use", "general": "Free"},
    {"htsno": "9025.11", "description": "Thermometers, liquid-filled, for direct reading", "general": "Free"},
    {"htsno": "9025.19", "description": "Other thermometers (digital, infrared)", "general": "Free"},
    {"htsno": "9027.10", "description": "Gas analysis apparatus (breathalyzers)", "general": "Free"},
    {"htsno": "9030.33", "description": "Multimeters without recording device", "general": "Free"},

    # Chapter 91: Clocks and Watches
    {"htsno": "9101.11", "description": "Wrist-watches, electrically operated, with mechanical display", "general": "51¢ each + 6.25% on case + 14% on strap/band"},
    {"htsno": "9102.11", "description": "Wrist-watches, not electrically operated, with automatic winding", "general": "40¢ each"},
    {"htsno": "9102.21", "description": "Wrist-watches, not electrically operated, no automatic winding", "general": "40¢ each"},
    {"htsno": "9104.00", "description": "Instrument panel clocks and clocks of a similar type for vehicles", "general": "Free"},

    # Chapter 92: Musical Instruments
    {"htsno": "9201.10", "description": "Upright pianos", "general": "4.7%"},
    {"htsno": "9201.20", "description": "Grand pianos", "general": "4.7%"},
    {"htsno": "9202.10", "description": "Violins and other string instruments played with a bow", "general": "Free"},
    {"htsno": "9204.10", "description": "Accordions", "general": "Free"},
    {"htsno": "9205.10", "description": "Brass-wind instruments (trumpets, trombones, tubas)", "general": "2.7%"},
    {"htsno": "9206.00", "description": "Percussion instruments (drums, cymbals, xylophone)", "general": "Free"},
    {"htsno": "9207.10", "description": "Keyboard instruments, other than accordions (keyboards, organs)", "general": "Free"},
    {"htsno": "9208.10", "description": "Music boxes", "general": "3.2%"},

    # Chapter 93: Arms and Ammunition
    {"htsno": "9301.20", "description": "Rocket launchers; flame-throwers", "general": "Free"},
    {"htsno": "9302.00", "description": "Revolvers and pistols", "general": "Free"},
    {"htsno": "9303.10", "description": "Muzzle-loading firearms", "general": "Free"},
    {"htsno": "9304.00", "description": "Other arms (spring, air or gas guns and pistols)", "general": "3.9%"},
    {"htsno": "9305.20", "description": "Parts and accessories for shotguns or rifles", "general": "Free"},
    {"htsno": "9306.30", "description": "Other cartridges and parts thereof (ammunition)", "general": "Free"},
    {"htsno": "9307.00", "description": "Swords, cutlasses, bayonets, lances and similar arms", "general": "Free"},

    # Chapter 94: Furniture, Bedding, Lamps
    {"htsno": "9401.10", "description": "Seats for aircraft", "general": "Free"},
    {"htsno": "9401.20", "description": "Seats for motor vehicles", "general": "Free"},
    {"htsno": "9401.30", "description": "Swivel seats with variable height adjustment (office chairs)", "general": "Free"},
    {"htsno": "9401.40", "description": "Seats other than garden seats or camping equipment, convertible into beds", "general": "Free"},
    {"htsno": "9401.61", "description": "Upholstered seats, of wood (wooden armchairs, sofas)", "general": "Free"},
    {"htsno": "9401.71", "description": "Upholstered seats of metal", "general": "Free"},
    {"htsno": "9401.80", "description": "Other seats (plastic chairs, bar stools)", "general": "Free"},
    {"htsno": "9402.10", "description": "Dentists' chairs and similar barber's chairs", "general": "Free"},
    {"htsno": "9403.10", "description": "Metal furniture for offices (filing cabinets, desks)", "general": "Free"},
    {"htsno": "9403.20", "description": "Other metal furniture (metal shelving, racks)", "general": "Free"},
    {"htsno": "9403.30", "description": "Wooden furniture for offices (wooden desks, bookcases)", "general": "Free"},
    {"htsno": "9403.40", "description": "Wooden furniture for kitchen (kitchen cabinets)", "general": "Free"},
    {"htsno": "9403.50", "description": "Wooden furniture for bedroom (beds, wardrobes)", "general": "Free"},
    {"htsno": "9403.60", "description": "Other wooden furniture (dining tables, coffee tables)", "general": "Free"},
    {"htsno": "9403.70", "description": "Furniture of plastics (plastic shelving, storage units)", "general": "Free"},
    {"htsno": "9403.82", "description": "Furniture of bamboo", "general": "Free"},
    {"htsno": "9404.10", "description": "Mattress supports", "general": "Free"},
    {"htsno": "9404.21", "description": "Mattresses of cellular rubber or plastics", "general": "3%"},
    {"htsno": "9404.29", "description": "Other mattresses (spring, foam, latex)", "general": "Free"},
    {"htsno": "9404.30", "description": "Sleeping bags", "general": "Free"},
    {"htsno": "9405.10", "description": "Chandeliers and other electric ceiling or wall lighting fittings", "general": "3.9%"},
    {"htsno": "9405.20", "description": "Electric table, desk, bedside or floor standing lamps", "general": "3.9%"},
    {"htsno": "9405.50", "description": "Non-electrical lamps and lighting fittings (candle holders)", "general": "6%"},

    # Chapter 95: Toys, Games and Sports Equipment
    {"htsno": "9501.00", "description": "Wheeled toys designed to be ridden by children (tricycles, scooters)", "general": "Free"},
    {"htsno": "9502.10", "description": "Dolls representing only human beings", "general": "Free"},
    {"htsno": "9503.00", "description": "Tricycles, scooters, pedal cars and similar wheeled toys; dolls' carriages; dolls; other toys; reduced-scale ('scale') models", "general": "Free"},
    {"htsno": "9504.20", "description": "Articles and accessories for billiards", "general": "Free"},
    {"htsno": "9504.30", "description": "Other games, operated by coins, banknotes (arcade games)", "general": "Free"},
    {"htsno": "9504.40", "description": "Playing cards", "general": "Free"},
    {"htsno": "9504.50", "description": "Video game consoles and machines, other than of subheading 9504.30", "general": "Free"},
    {"htsno": "9504.90", "description": "Other game equipment (chess, checkers, board games)", "general": "Free"},
    {"htsno": "9505.10", "description": "Articles for Christmas festivities (Christmas decorations)", "general": "Free"},
    {"htsno": "9506.11", "description": "Skis (alpine skiing)", "general": "2.6%"},
    {"htsno": "9506.21", "description": "Sailboards (windsurfing boards)", "general": "Free"},
    {"htsno": "9506.31", "description": "Golf clubs, complete", "general": "4.4%"},
    {"htsno": "9506.40", "description": "Articles and equipment for table-tennis", "general": "Free"},
    {"htsno": "9506.51", "description": "Lawn-tennis rackets", "general": "Free"},
    {"htsno": "9506.61", "description": "Lawn-tennis balls", "general": "Free"},
    {"htsno": "9506.62", "description": "Inflatable balls (footballs, basketballs, volleyballs)", "general": "Free"},
    {"htsno": "9506.91", "description": "Articles and equipment for general physical exercise (gym equipment)", "general": "4.6%"},
    {"htsno": "9507.10", "description": "Fishing rods", "general": "Free"},
    {"htsno": "9507.30", "description": "Fishing reels", "general": "Free"},
    {"htsno": "9508.10", "description": "Roundabouts, swings, shooting galleries and other fairground amusements", "general": "Free"},

    # Chapter 96: Miscellaneous Manufactured Articles
    {"htsno": "9601.10", "description": "Worked ivory, articles of ivory", "general": "Free"},
    {"htsno": "9602.00", "description": "Worked vegetable or mineral carving material (coral, bone)", "general": "Free"},
    {"htsno": "9603.10", "description": "Brooms and brushes of twigs or other vegetable materials (brooms)", "general": "Free"},
    {"htsno": "9603.21", "description": "Toothbrushes", "general": "Free"},
    {"htsno": "9603.29", "description": "Other shaving, hair, nail brushes", "general": "Free"},
    {"htsno": "9604.00", "description": "Hand sieves and hand riddles", "general": "Free"},
    {"htsno": "9605.00", "description": "Travel sets for personal toilet, sewing or shoe cleaning", "general": "8.1%"},
    {"htsno": "9606.10", "description": "Press-fasteners, snap-fasteners and press-studs", "general": "Free"},
    {"htsno": "9606.21", "description": "Buttons of plastics, not covered with textile material", "general": "Free"},
    {"htsno": "9607.11", "description": "Slide fasteners fitted with chain scoops of base metal (metal zippers)", "general": "Free"},
    {"htsno": "9607.19", "description": "Other slide fasteners (nylon zippers, plastic zippers)", "general": "Free"},
    {"htsno": "9608.10", "description": "Ballpoint pens", "general": "Free"},
    {"htsno": "9608.20", "description": "Felt tipped and other porous-tipped pens", "general": "Free"},
    {"htsno": "9608.30", "description": "Fountain pens, stylograph pens", "general": "Free"},
    {"htsno": "9609.10", "description": "Pencils and crayons, with leads encased in a rigid sheath", "general": "14¢/gross + 4.3%"},
    {"htsno": "9610.00", "description": "Slates and boards, with writing or drawing surfaces (whiteboards, blackboards)", "general": "Free"},
    {"htsno": "9611.00", "description": "Date, sealing or numbering stamps, and the like (rubber stamps)", "general": "Free"},
    {"htsno": "9612.10", "description": "Inked ribbon (typewriter ribbons, printer ribbons)", "general": "Free"},
    {"htsno": "9613.10", "description": "Pocket lighters, gas fuelled, non-refillable", "general": "8.1%"},
    {"htsno": "9614.00", "description": "Smoking pipes (including pipe bowls) and cigar or cigarette holders", "general": "Free"},
    {"htsno": "9615.11", "description": "Combs, hair-slides and the like of hard rubber or plastics", "general": "Free"},
    {"htsno": "9616.10", "description": "Scent sprays and similar toilet sprays (perfume atomizers)", "general": "Free"},
    {"htsno": "9617.00", "description": "Vacuum flasks and other vacuum vessels (thermos bottles)", "general": "Free"},
    {"htsno": "9618.00", "description": "Tailors' dummies and other lay figures (mannequins)", "general": "Free"},
    {"htsno": "9619.00", "description": "Sanitary towels (pads) and tampons, napkins, nappies", "general": "Free"},
    {"htsno": "9620.00", "description": "Monopods, bipods, tripods and similar articles (camera stands)", "general": "Free"},

    # Chapter 33: Cosmetics and Toiletries (commonly shipped)
    {"htsno": "3303.00", "description": "Perfumes and toilet waters", "general": "Free"},
    {"htsno": "3304.10", "description": "Lip make-up preparations (lipstick, lip gloss)", "general": "Free"},
    {"htsno": "3304.20", "description": "Eye make-up preparations (mascara, eye shadow, eyeliner)", "general": "Free"},
    {"htsno": "3304.30", "description": "Manicure or pedicure preparations (nail polish)", "general": "Free"},
    {"htsno": "3304.91", "description": "Powders, whether or not compressed (face powder, blush)", "general": "Free"},
    {"htsno": "3304.99", "description": "Other beauty or make-up preparations (foundation, concealer)", "general": "Free"},
    {"htsno": "3305.10", "description": "Shampoos", "general": "Free"},
    {"htsno": "3305.20", "description": "Preparations for permanent waving or straightening of hair", "general": "Free"},
    {"htsno": "3305.30", "description": "Hair lacquers (hair spray)", "general": "Free"},
    {"htsno": "3305.90", "description": "Other preparations for use on the hair (conditioner, hair serum)", "general": "Free"},
    {"htsno": "3306.10", "description": "Dentifrices (toothpaste)", "general": "Free"},
    {"htsno": "3306.20", "description": "Yarn used to clean between the teeth (dental floss)", "general": "Free"},
    {"htsno": "3307.10", "description": "Pre-shave, shaving or after-shave preparations", "general": "Free"},
    {"htsno": "3307.20", "description": "Personal deodorants and antiperspirants", "general": "Free"},
    {"htsno": "3307.30", "description": "Perfumed bath salts and other bath preparations", "general": "Free"},
    {"htsno": "3307.41", "description": "Agarbatti and other odoriferous preparations (incense sticks)", "general": "Free"},
    {"htsno": "3307.49", "description": "Preparations for perfuming or deodorizing rooms (air fresheners)", "general": "Free"},

    # Chapter 32: Paints, Varnishes (commonly shipped)
    {"htsno": "3208.10", "description": "Paints and varnishes based on polyesters, in non-aqueous medium", "general": "3.7%"},
    {"htsno": "3209.10", "description": "Paints and varnishes based on acrylic or vinyl polymers, in aqueous medium", "general": "5.1%"},
    {"htsno": "3213.10", "description": "Artists' water colours", "general": "Free"},
    {"htsno": "3215.11", "description": "Printing ink, black", "general": "1.8%"},

    # Additional common courier items
    {"htsno": "4202.11", "description": "Trunks, suit-cases, vanity-cases, brief-cases with outer surface of leather", "general": "8%"},
    {"htsno": "4202.12", "description": "Trunks, suit-cases (luggage) with outer surface of plastics or textile", "general": "20%"},
    {"htsno": "4202.19", "description": "Trunks, suit-cases, travel bags, other outer surface", "general": "20%"},
    {"htsno": "4202.21", "description": "Handbags, whether or not with shoulder strap, of leather", "general": "9.2%"},
    {"htsno": "4202.22", "description": "Handbags of sheeting of plastics or textile materials", "general": "16%"},
    {"htsno": "4202.29", "description": "Handbags of other materials (canvas bags, fabric bags)", "general": "17%"},
    {"htsno": "4202.31", "description": "Articles of a kind normally carried in the pocket of leather (wallets)", "general": "8%"},
    {"htsno": "4202.32", "description": "Articles of a kind normally carried in the pocket of plastics (wallets)", "general": "20%"},
    {"htsno": "4202.91", "description": "Other trunks, suit-cases, travel-bags, handbags of leather", "general": "Free"},
    {"htsno": "4202.92", "description": "Other bags of plastics or textile (backpacks, gym bags)", "general": "17.6%"},
    {"htsno": "4202.99", "description": "Other bags, cases of other material", "general": "20%"},
    {"htsno": "6116.10", "description": "Gloves impregnated, coated or covered with plastics or rubber, knitted", "general": "Free"},
    {"htsno": "6116.91", "description": "Gloves of wool or fine animal hair, knitted", "general": "Free"},
    {"htsno": "6116.93", "description": "Gloves of synthetic fibres, knitted", "general": "18.6%"},

    # Sports and fitness (additional)
    {"htsno": "9506.70", "description": "Ice skates and roller skates, including skating boots with skates attached", "general": "Free"},
    {"htsno": "9506.99", "description": "Other articles and equipment for sports, not elsewhere specified (yoga mats)", "general": "4%"},
    {"htsno": "9506.32", "description": "Golf balls", "general": "Free"},

    # Baby products
    {"htsno": "6209.20", "description": "Babies' garments and clothing accessories of cotton, not knitted", "general": "11.5%"},
    {"htsno": "9403.83", "description": "Furniture of rattan (baby cribs, play yards)", "general": "Free"},
    {"htsno": "9404.90", "description": "Other articles of bedding and similar furnishing (baby quilts)", "general": "Free"},

    # Computer accessories and electronics
    {"htsno": "8443.99", "description": "Parts and accessories for printers, copiers (ink cartridges, toner)", "general": "Free"},
    {"htsno": "8504.31", "description": "Transformers having a power handling capacity ≤1 kVA", "general": "Free"},
    {"htsno": "8504.50", "description": "Inductors (coils, chokes)", "general": "Free"},
    {"htsno": "8536.90", "description": "Other apparatus for switching/protecting electrical circuits (circuit breakers)", "general": "Free"},
    {"htsno": "8544.20", "description": "Coaxial cables and other coaxial electric conductors", "general": "Free"},
    {"htsno": "8544.30", "description": "Ignition wiring sets and other wiring sets of a kind used in vehicles", "general": "Free"},
    {"htsno": "8547.10", "description": "Insulating fittings of ceramics", "general": "Free"},

    # Office supplies and stationery
    {"htsno": "4817.10", "description": "Envelopes of paper or paperboard", "general": "Free"},
    {"htsno": "4820.10", "description": "Registers, account books, notebooks, order books of paper", "general": "Free"},
    {"htsno": "4820.20", "description": "Exercise books of paper", "general": "Free"},
    {"htsno": "4820.30", "description": "Binders, folders and file covers of paper", "general": "Free"},
    {"htsno": "4820.50", "description": "Albums for samples or collections of paper", "general": "Free"},
    {"htsno": "4821.10", "description": "Printed paper or paperboard labels", "general": "Free"},
    {"htsno": "4823.20", "description": "Filter paper and paperboard", "general": "Free"},
    {"htsno": "9608.40", "description": "Propelling or sliding pencils (mechanical pencils)", "general": "Free"},
    {"htsno": "9608.50", "description": "Sets of articles from two or more of pens/markers/pencils", "general": "Free"},
]
